spring.application.name=venda-veiculos-service

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:venda_veiculos_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

app.internal-token=${INTERNAL_TOKEN:dev-only-token}

management.endpoints.web.exposure.include=health,info,metrics,prometheus
